name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PDM
      run: |
        pip install pdm

    - name: Install dependencies
      run: |
        pdm install -G test

    - name: Start PostgreSQL
      run: |
        echo "Starting PostgreSQL..."
        docker compose -f tests/setup_env/pgsql/docker-compose.yml up -d --wait

    - name: Start Milvus services
      run: |
        echo "Starting Milvus and its dependencies..."
        docker compose -f tests/setup_env/milvus/docker-compose.yml up -d --wait

    - name: Run demo operation tests
      run: |
        pdm run pytest tests/test_demo_operations.py -v
      env:
        MILVUS_URI: http://localhost:19530
        PG_CONN: postgresql://postgres:admin@localhost:5432/default